function UseCode(Text)
			game:GetService("ReplicatedStorage").Remotes.Redeem:InvokeServer(Text)
		end
		UseCode("GAMERROBOT_YT")
		UseCode("kittgaming")
		UseCode("Sub2Fer999")
		UseCode("Enyu_is_Pro")
		UseCode("Magicbus")
		UseCode("JCWK")
		UseCode("Starcodeheo")
		UseCode("Bluxxy")
		UseCode("THEGREATACE")
		UseCode("SUB2GAMERROBOT_EXP1")
		UseCode("Sub2OfficialNoobie")
		UseCode("StrawHatMaine")
		UseCode("SUB2NOOBMASTER123  ")
		UseCode("Sub2Daigrock")
		UseCode("Axiore")
		UseCode("TantaiGaming")
